name: Publish and deploy

on:
  push:
    branches:
      - action-dev-1
      - mainline
jobs:
  pull_and_deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: SSH, pull down, and start
      uses: appleboy/ssh-action@master
      with:
        host: ssh.brydonleonard.com
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIV_KEY }}
        port: 22
        command_timeout: 30m
        script: | 
          # Pull the image from docker hub
          docker image pull brydonleonard/gate_key:action-dev-1

          # Create the volume. Does nothing if the volume exists
          docker volume create \
            --driver local \
            --opt type=none \
            --opt device=/usr/local/GateKey/persistent \
            --opt o=bind \
            GateKeyVolume

          # Stop and delete the old container
          # Suppress errors in case the old container doesn't exist or isn't running
          docker stop GateKey || true
          docker rm GateKey || true

          # Start the new container
          sudo docker run \
            --env GATE_KEY_ALLOWED_CALLERS=${{ secrets.GATE_KEY_ALLOWED_CALLERS }} \
            --env GATE_KEY_TELEGRAM_BOT_TOKEN=${{ secrets.GATE_KEY_TELEGRAM_BOT_TOKEN }} \
            --env GATE_KEY_CERT_PASSWORD=${{ secrets.GATE_KEY_CERT_PASSWORD }} \
            --volume GateKeyVolume:/persistent \
            --name=GateKey \
            brydonleonard/gate_key:action-dev-1
          
